In [19]:
import numpy as np
import pandas as pd
import sklearn

from sklearn.datasets import load_boston
df= load_boston()

df.keys()

print(df.data)

boston=pd.DataFrame(df.data, columns=df.feature_names)
boston.head()

boston["COST"] =df.target
boston.head()

boston.isnull()

boston.isnull().sum()

from sklearn.model_selection import train_test_split
X= boston.drop('COST', axis=1)
Y= boston['COST']

X_train, X_test, Y_train, Y_test= train_test_split(X,Y, test_size=0.7, random_state=9)
print(X_train.shape)
print(Y_test.shape)
print(Y_train.shape)
print(Y_test.shape)

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

lin_model=LinearRegression()
lin_model.fit(X_train, Y_train)

Y_train_predict= lin_model.predict(X_train)
md= (np.sqrt(mean_squared_error(Y_train,Y_train_predict)))
print("The model performance for talking set")
print('MD is {}'.format(md))
print("\n")

Y_test_predict= lin_model.predict(X_test)
md= (np.sqrt(mean_squared_error(Y_train,Y_train_predict)))
print("The model performance for testing set")
print('MD is {}'.format(md))
print(".\n")

[[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]
(151, 13)
(355,)
(151,)
(355,)
The model performance for talking set
MD is 4.974071297280925


The model performance for testing set
MD is 4.974071297280925
.

